version: '3.8'

services:
  database:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - iki-data:/var/lib/mysql
    networks:
      - iki

  iki-backend:
    image: mishobo/iki-web-apis:002
    ports:
      - "8080:8080"
    networks:
      - iki

  admin-frontend:
    image: mishobo/admin-app:1.0.0
    ports:
      - '3000:80'
    volumes:
      - ./src:/app/src

volumes:
  iki-data:
    driver: local

networks:
  iki: {}