server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://75.119.143.18:3306/iki?createDatabaseIfNotExist=true
    username: abdallah
    password: mishobo@31875595
    dialect: org.hibernate.dialect.MariaDBDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



iki:
  app:
    jwtSecret: ======================iki=Spring===========================
    jwtExpirationMs: 86400000