server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://137.184.191.7:3306/iki?createDatabaseIfNotExist=true
    username: root
    password: 123456
    dialect: org.hibernate.dialect.MariaDBDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



iki:
  app:
    jwtSecret: ======================iki=Spring===========================
    jwtExpirationMs: 86400000