spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/iki?createDatabaseIfNotExist=true
    username: root
    password: 31875595
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

iki:
  app:
    jwtSecret: ======================iki=Spring===========================
    jwtExpirationMs: 86400000